### ISSUE TITLE
Can't create tests for classes that invoke methods inside constructor

### ISSUE THREAD

**Issue by richardpon** [box/TestScribe#8]
(This could be a Shmock limitation)

I generated a test for Anemometer_PostProcess_Processor::run() and the generated test fails due to:

(The Gerrit is http://scm.dev.box.net:8080/#/c/224461/1/lib/Anemometer/PostProcess/Processor.php)

1) Anemometer_PostProcess_ProcessorGenTest::test_runProcessedNoRecordsForZeroLimit
Expectation failed for method name is equal to <string:getConvertedType> when invoked at sequence index 0.
Mocked method does not exist.

phar:///usr/local/Cellar/phpunit/4.3.4/libexec/phpunit-4.3.4.phar/phpunit/TextUI/Command.php:186
phar:///usr/local/Cellar/phpunit/4.3.4/libexec/phpunit-4.3.4.phar/phpunit/TextUI/Command.php:138

**Comment by richardpon** [comment]
The workaround was to not call any method in the constructor as shown in this review:

http://scm.dev.box.net:8080/#/c/224457/1/lib/Anemometer/PostProcess/Processor.php

**Comment by HappyRay** [comment]
It looks like \Shmock\PHPUnitMockInstance::replay method will construct the real object first before the expectations are set. i.e. you can't rely on partial mocking within the constructor. 

I would recommend not calling one's own protected or public methods of its constructor anyway.

**Comment by HappyRay** [comment]
Add to the limitation wiki page.

**Comment by HappyRay** [comment]
This is limited by the current implementation of shmock.
